import React, { useState } from 'react';
import { FileText, Copy, Check, Download, ShieldCheck, AlertOctagon, Sparkles } from 'lucide-react';

interface CioVerdict {
  decision: 'INVEST' | 'PASS';
  confidenceScore: number;
  targetPrice12m: number;
  expectedReturnPercent: number;
  investmentHorizon: string;
  riskRating: 'LOW' | 'MODERATE' | 'HIGH' | 'EXTREME';
  executiveSummary: string;
  keyThesisPoints: string[];
  primaryRiskFactor: string;
  actionableAdvice: string;
}

interface Props {
  verdict?: CioVerdict;
  companyName: string;
  symbol: string;
  currency: string;
}

export const ExecutiveSummary: React.FC<Props> = ({ verdict, companyName, symbol, currency }) => {
  const [copied, setCopied] = useState(false);

  if (!verdict) return null;

  const currencySymbol = currency === 'INR' ? '₹' : '$';

  const generateMarkdownReport = () => {
    return `# Aegis Alpha Studio — Quantum Wealth Terminal
## Autonomous AI Investment Research Report: ${companyName} (${symbol})
**Date**: ${new Date().toLocaleDateString()}
**Verdict**: ${verdict.decision} (Alpha Confidence Score: ${verdict.confidenceScore}/100)
**12-Month Target Price**: ${currencySymbol}${verdict.targetPrice12m} (${verdict.expectedReturnPercent >= 0 ? '+' : ''}${verdict.expectedReturnPercent}% Expected Return)
**Risk Rating**: ${verdict.riskRating}
**Investment Horizon**: ${verdict.investmentHorizon}

---

### Executive Synthesis
${verdict.executiveSummary}

---

### Key Thesis Points
${verdict.keyThesisPoints.map(p => `- ${p}`).join('\n')}

---

### Primary Risk Factor & Vulnerability
**⚠️ ${verdict.primaryRiskFactor}**

---

### CIO Actionable Portfolio Advice
> ${verdict.actionableAdvice}

---
*Report generated autonomously by VanguardIQ / Aegis Alpha Studio multi-agent LangGraph pipeline (InsideIIM × Altuni AI Labs).*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([generateMarkdownReport()], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `${symbol}_Aegis_Alpha_Research_Report.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="glass-panel p-8 mb-12 border border-[var(--border-subtle)]">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-6 mb-6 border-b border-[var(--border-subtle)] gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-[rgba(96,239,255,0.1)] border border-[rgba(96,239,255,0.2)]">
            <FileText className="w-6 h-6 text-[var(--emerald-teal)]" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-white tracking-wide">
              CIO Executive Synthesis & Actionable Advice
            </h3>
            <p className="text-xs text-[var(--text-muted)]">
              Comprehensive institutional investment memo generated by multi-agent consensus
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="btn-secondary text-xs py-2 px-3"
            title="Copy Report as Markdown"
          >
            {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied Markdown!' : 'Copy Thesis'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="btn-secondary text-xs py-2 px-3 border-[var(--emerald-teal)] text-[var(--emerald-teal)]"
            title="Download Report as .md file"
          >
            <Download className="w-4 h-4" />
            <span>Export .MD</span>
          </button>
        </div>
      </div>

      {/* Executive Summary Body */}
      <div className="prose prose-invert max-w-none text-sm leading-relaxed text-[var(--text-main)] whitespace-pre-line mb-8 font-sans">
        {verdict.executiveSummary}
      </div>

      {/* Key Thesis Points & Actionable Advice Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-[rgba(255,255,255,0.05)]">
        {/* Thesis Points */}
        <div className="p-5 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.05)]">
          <span className="text-xs font-mono font-bold uppercase tracking-wider text-[var(--emerald-primary)] flex items-center gap-2 mb-3">
            <Sparkles className="w-4 h-4" /> Core Investment Thesis Pillars
          </span>
          <ul className="space-y-2.5 text-xs text-[var(--text-main)]">
            {verdict.keyThesisPoints.map((point, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-[var(--emerald-primary)] font-bold shrink-0">•</span>
                <span className="leading-normal">{point}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Actionable Advice & Risk Factor */}
        <div className="flex flex-col justify-between gap-4">
          <div className="p-4 rounded-xl bg-[rgba(255,75,75,0.08)] border border-[rgba(255,75,75,0.2)]">
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-[var(--crimson-alert)] flex items-center gap-1.5 mb-1">
              <AlertOctagon className="w-4 h-4" /> Primary Risk to Monitor
            </span>
            <p className="text-xs text-[var(--text-main)] font-semibold mt-1">
              {verdict.primaryRiskFactor}
            </p>
          </div>

          <div className="p-5 rounded-xl bg-[rgba(0,255,135,0.08)] border border-[rgba(0,255,135,0.2)] flex-1 flex flex-col justify-center">
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-[var(--emerald-primary)] flex items-center gap-1.5 mb-1">
              <ShieldCheck className="w-4 h-4" /> CIO Actionable Portfolio Advice
            </span>
            <p className="text-xs text-white font-bold leading-relaxed mt-1">
              {verdict.actionableAdvice}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
